on:
  - push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo 
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

      - name: install deps
        run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - name: Tests
        run: | 
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec --format documentation \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"

      - name: Artifact creation
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: /tmp/test-results
